# Generated by Django 3.1.3 on 2021-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
